export const tygerAnswers = [
  "Suck it, hooman",
  "Are you kidding me?",
  "Go away, I'm sleeping",
  "Yes, definitely, when you feed me tuna",
  "No",
  "Where is my food?",
  "The nerve of you to ask me such a thing!",
  "Yes, unfortunately",
  "Go ask Angel. I'm tired",
  "Do I look serious to you?",
  "Ask again later. I'm eating",
  "Did you know that cats were once worshipped as gods?",
  "I'll answer if you brush me",
  "Allow me to sharpen my claws and get back to you",
  "Don't count on it",
  "Where is my tuna, hooman?",
  "My sources say no. Ask my mom.",
  "It is extremely difficult to know everything",
  "Outlook not so good. Unless you have tuna.",
  "Very doubtful",
];
